import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));
const check=(name,value)=>{checks.push({name,passed:!!value});if(!value)throw new Error(name)};
await page.goto('http://127.0.0.1:8769');await page.waitForSelector('#overview:not([hidden])');
check('real sample count',await page.locator('#stat-jobs').innerText()==='100');
check('single baseline',await page.locator('#stat-history').innerText()==='1');
check('no horizontal overflow desktop',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'records/desktop.png',fullPage:true});
await page.locator('[data-learning]').click();check('Python evidence filter',await page.locator('#results-count').innerText()==='18 条匹配 / 100 条本次样本');
await page.locator('.job-title').first().click();check('details open',await page.locator('#detail').evaluate(e=>e.open));check('exact source evidence visible',await page.locator('#detail-content').innerText().then(x=>x.includes('python')));await page.keyboard.press('Escape');check('escape closes detail',await page.locator('#detail').evaluate(e=>!e.open));
await page.locator('.save').first().click();await page.locator('#only-saved').check();check('saved filter works',await page.locator('.job').count()===1);await page.reload();await page.waitForSelector('#jobs:not([hidden])');await page.locator('#only-saved').check();check('saved persists across reload',await page.locator('.job').count()===1);
await page.locator('#reset').click();await page.locator('#search').fill('no-such-job-9383838');check('empty state',await page.locator('#empty').isVisible());await page.locator('#empty-reset').click();check('reset full sample',await page.locator('#results-count').innerText()==='100 条匹配 / 100 条本次样本');
await page.locator('#next').click();check('pagination next',await page.locator('#page-number').innerText()==='2 / 10');await page.locator('#prev').click();check('pagination previous',await page.locator('#page-number').innerText()==='1 / 10');
await page.locator('#category').selectOption('Software Engineering');check('category scoped subset',await page.locator('#results-count').innerText()==='6 条匹配 / 100 条本次样本');
await page.locator('[data-route="method"]').click();check('method coverage visible',await page.locator('#coverage').innerText().then(x=>x.includes('更多页')));await page.goBack();check('browser back restores jobs',await page.locator('#jobs').isVisible());
await page.setViewportSize({width:390,height:844});await page.locator('[data-route="overview"]').click();check('no horizontal overflow mobile',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'records/mobile.png',fullPage:true});
await page.locator('[data-route="jobs"]').click();check('mobile jobs no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.job-title').first().click();check('mobile modal fits',await page.locator('#detail').evaluate(e=>e.getBoundingClientRect().width<innerWidth));await page.locator('.close').click();
await page.locator('[data-route="method"]').click();check('mobile method no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('zero browser errors',errors.length===0);
await writeFile('records/browser-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),browser:'Cloud headless Chromium; local static preview',checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();
