import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
const {JSDOM}=createRequire(import.meta.url)('jsdom');
const html=await readFile('dist/index.html','utf8'),js=await readFile('dist/app.js','utf8'),data=JSON.parse(await readFile('dist/data.json','utf8'));
const dom=new JSDOM(html,{url:'http://localhost:8769/',runScripts:'outside-only'}),w=dom.window;
w.fetch=async()=>({ok:true,json:async()=>data});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
const q=s=>w.document.querySelector(s);const check=(name,value)=>{checks.push({name,passed:!!value});if(!value)throw new Error(name)};const checks=[];
await w.eval(`(async()=>{${js}\n})()`);
check('real count and baseline',q('#stat-jobs').textContent==='17'&&q('#stat-history').textContent==='1');
check('one baseline disables comparison',q('#compare-history').disabled);check('history baseline explanation',q('#history-comparison').textContent.includes('只有一份真实基线'));
check('first ten rendered',w.document.querySelectorAll('.job').length===10);
q('[data-learning]').click();check('skill selection evidence count',q('#results-count').textContent==='12 条匹配 / 17 条技术职能组');
q('.job-title').click();check('details contain matched Python token',q('#detail').open&&q('#detail-content').textContent.includes('python'));q('.close').click();check('detail close action',!q('#detail').open);
q('.save').click();q('#only-saved').checked=true;q('#only-saved').dispatchEvent(new w.Event('change'));check('saved-only filter',w.document.querySelectorAll('.job').length===1);check('local persistence written',JSON.parse(w.localStorage.getItem('job-observatory-saved')).length===1);
q('#reset').click();q('#search').value='NONEXISTENT-983423';q('#search').dispatchEvent(new w.Event('input'));check('empty search state',!q('#empty').hidden);q('#empty-reset').click();check('reset restores total',q('#results-count').textContent==='17 条匹配 / 17 条技术职能组');
q('#next').click();check('next page',q('#page-number').textContent==='2 / 2');q('#prev').click();check('previous page',q('#page-number').textContent==='1 / 2');
q('#category').value='Software Engineering';q('#category').dispatchEvent(new w.Event('change'));check('source-category subset',q('#results-count').textContent==='6 条匹配 / 17 条技术职能组');
w.location.hash='method';w.dispatchEvent(new w.HashChangeEvent('hashchange'));check('method navigation',!q('#method').hidden&&q('#jobs').hidden);check('coverage disclosure',q('#coverage').textContent.includes('更多页'));check('all rendered source links canonical',[...w.document.querySelectorAll('a.source')].every(e=>e.href.startsWith('https://jobicy.com/jobs/')));
check('no raw listing html rendered',w.document.querySelectorAll('script').length===1);
q('[data-cohort="software"]').click();check('software cohort count and denominator',q('#stat-jobs').textContent==='6'&&q('#denominator').textContent==='分母：6 条软件工程岗位');check('cohort switch clears category filter',q('#category').value==='');
q('[data-cohort="all"]').click();check('all-source cohort is still available',q('#stat-jobs').textContent==='100'&&q('#results-count').textContent==='100 条匹配 / 100 条全样本组');q('[data-learning]').click();check('all-source Python denominator is independent',q('#results-count').textContent==='18 条匹配 / 100 条全样本组');
q('#cohort-select').value='technical';q('#cohort-select').dispatchEvent(new w.Event('change'));check('jobs cohort updates overview consistently',q('#stat-jobs').textContent==='17'&&q('#skill').value==='');check('technical learning evidence is 12 of17',q('#learning-content').textContent.includes('12/17'));check('explicit original-source denominator',q('#cohort-scope').textContent.includes('17/100'));
const zero=new JSDOM(html,{url:'http://localhost:8769/',runScripts:'outside-only'});zero.window.fetch=async()=>({ok:true,json:async()=>({...data,jobs:data.jobs.map(j=>({...j,categories:['Sales']}))})});zero.window.scrollTo=()=>{};await zero.window.eval(`(async()=>{${js}\n})()`);check('empty technical cohort has zero denominator',zero.window.document.querySelector('#stat-jobs').textContent==='0');check('empty cohort never borrows skill counts',zero.window.document.querySelectorAll('.bar-row').length===0&&zero.window.document.querySelector('#skills-chart').textContent.includes('不会从其它组借用结论'));zero.window.close();
await writeFile('records/dom-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),method:'JSDOM with fetch and dialog polyfills; verifies application logic only, not browser layout/accessibility',checks},null,2)+'\n');console.log(JSON.stringify({passed:checks.length}));w.close();
