import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
const {JSDOM}=createRequire(import.meta.url)('jsdom');
const html=await readFile('dist/index.html','utf8'),js=await readFile('dist/app.js','utf8'),data=JSON.parse(await readFile('dist/data.json','utf8'));
const dom=new JSDOM(html,{url:'http://localhost:8769/',runScripts:'outside-only'}),w=dom.window;
w.fetch=async()=>({ok:true,json:async()=>data});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
const q=s=>w.document.querySelector(s);const check=(name,value)=>{checks.push({name,passed:!!value});if(!value)throw new Error(name)};const checks=[];
await w.eval(`(async()=>{${js}\n})()`);
check('real count and baseline',q('#stat-jobs').textContent==='100'&&q('#stat-history').textContent==='1');
check('first ten rendered',w.document.querySelectorAll('.job').length===10);
q('[data-learning]').click();check('skill selection evidence count',q('#results-count').textContent==='18 条匹配 / 100 条本次样本');
q('.job-title').click();check('details contain matched Python token',q('#detail').open&&q('#detail-content').textContent.includes('python'));q('.close').click();check('detail close action',!q('#detail').open);
q('.save').click();q('#only-saved').checked=true;q('#only-saved').dispatchEvent(new w.Event('change'));check('saved-only filter',w.document.querySelectorAll('.job').length===1);check('local persistence written',JSON.parse(w.localStorage.getItem('job-observatory-saved')).length===1);
q('#reset').click();q('#search').value='NONEXISTENT-983423';q('#search').dispatchEvent(new w.Event('input'));check('empty search state',!q('#empty').hidden);q('#empty-reset').click();check('reset restores total',q('#results-count').textContent==='100 条匹配 / 100 条本次样本');
q('#next').click();check('next page',q('#page-number').textContent==='2 / 10');q('#prev').click();check('previous page',q('#page-number').textContent==='1 / 10');
q('#category').value='Software Engineering';q('#category').dispatchEvent(new w.Event('change'));check('source-category subset',q('#results-count').textContent==='6 条匹配 / 100 条本次样本');
w.location.hash='method';w.dispatchEvent(new w.HashChangeEvent('hashchange'));check('method navigation',!q('#method').hidden&&q('#jobs').hidden);check('coverage disclosure',q('#coverage').textContent.includes('更多页'));check('all rendered source links canonical',[...w.document.querySelectorAll('a.source')].every(e=>e.href.startsWith('https://jobicy.com/jobs/')));
check('no raw listing html rendered',w.document.querySelectorAll('script').length===1);
await writeFile('records/dom-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),method:'JSDOM with fetch and dialog polyfills; verifies application logic only, not browser layout/accessibility',checks},null,2)+'\n');console.log(JSON.stringify({passed:checks.length}));w.close();
