import {strict as assert} from 'node:assert';
import {readFile,writeFile} from 'node:fs/promises';
const {default:worker,bootstrap,sync,dataResponse,compare,normalize}=await import('../dist/server/index.js');
class Bucket{constructor(){this.map=new Map()}async get(k){const x=this.map.get(k);return x?{...x,json:async()=>JSON.parse(x.body)}:null}async head(k){return this.map.get(k)||null}async put(k,body,o={}){if(o.onlyIf?.etagDoesNotMatch==='*'&&this.map.has(k))return null;const x={key:k,body,customMetadata:o.customMetadata||{},etag:'test'};this.map.set(k,x);return x}async list(o){return {objects:[...this.map.values()].filter(x=>x.key.startsWith(o.prefix)),truncated:false}}}
const b=new Bucket(),checks=[];const check=(name,value)=>{assert(value,name);checks.push({name,passed:true})};
await bootstrap(b);let d=await dataResponse(b);check('baseline durable readback',d.jobs.length===100&&d.history.length===1&&d.syncInfo.storage==='r2');await bootstrap(b);check('bootstrap idempotent',(await dataResponse(b)).history.length===1);
const todayText=(await readFile('dist/server/index.js','utf8')).replaceAll('2026-10-06T17:56:43+00:00',new Date().toISOString());const todayRuntime=await import('data:text/javascript;base64,'+Buffer.from(todayText).toString('base64'));const nd=await todayRuntime.sync(new Bucket(),()=>{throw Error('must_not_fetch')});check('same-day sync skips source',(await nd.json()).status==='not_due');
check('extractor boundaries',(await normalize({id:1,url:'https://jobicy.com/jobs/test',jobTitle:'JavaScript engineer',companyName:'Test',jobDescription:'We go forward with C++ and Golang',jobIndustry:[],jobType:[]})).skills.every(s=>s.skill!=='Java'));
check('cross-version comparison refused',!compare({extractorVersion:'v1'},{extractorVersion:'v2'}).comparable);
check('missing classified as notInLatestSample',compare({extractorVersion:'v2',sourceScope:'a',jobs:[{id:'1',recordHash:'a'}]},{extractorVersion:'v2',sourceScope:'a',jobs:[]}).notInLatestSample[0]==='1');
const baseline=d;const aged={...d,observedAt:'2020-01-01T00:00:00Z'};const fail=new Bucket();const original=b.map.values().next().value;fail.map.set('snapshots/2020-01-01T00:00:00Z.json',{key:'snapshots/2020-01-01T00:00:00Z.json',body:JSON.stringify(aged),customMetadata:{observedAt:aged.observedAt,count:'100',responseSha256:'test'}});
// Replace baseline read date only in a separate test module, never real snapshot assets.
const workerText=await readFile('dist/server/index.js','utf8');const testModule=workerText.replaceAll('2026-10-06T17:56:43+00:00','2020-01-01T00:00:00Z');const testRuntime=await import('data:text/javascript;base64,'+Buffer.from(testModule).toString('base64'));
const r=await testRuntime.sync(fail,async()=>new Response('unavailable',{status:503}));check('failure returns 502',r.status===502);const failed=await testRuntime.dataResponse(fail);check('failure preserves snapshot',failed.jobs.length===100&&failed.history.length===1&&failed.syncInfo.status==='failed');let called=false;const again=await testRuntime.sync(fail,async()=>{called=true});check('hourly claim prevents duplicate source call',again.status===409&&!called);
const good=new Bucket();const one={id:881,url:'https://jobicy.com/jobs/test-fixture',jobTitle:'Python Engineer',companyName:'TEST FIXTURE ONLY',jobDescription:'Python SQL',jobIndustry:['Software Engineering'],jobType:['Full-Time'],jobGeo:'Worldwide'};const done=await testRuntime.sync(good,async()=>new Response(JSON.stringify({success:true,jobs:[one,one],hasMore:true})));check('successful snapshot append',done.status===200&&(await done.json()).status==='succeeded');const gd=await testRuntime.dataResponse(good);check('deduplicate and retain history',gd.jobs.length===1&&gd.history.length===2);check('new snapshot uses explicit scope',gd.sourceScope==='jobicy:first-page:100:unfiltered');
const forbidden=await worker.fetch(new Request('https://example.com/api/bootstrap',{method:'POST',headers:{origin:'https://evil.example'}}),{BUCKET:b});check('cross-origin writes rejected',forbidden.status===403);const unavailable=await worker.fetch(new Request('https://example.com/api/data'),{});check('missing binding explicit 503',unavailable.status===503);const reader=await worker.fetch(new Request('https://example.com/api/data'),{BUCKET:b});check('data route returns durable data',reader.status===200&&(await reader.json()).jobs.length===100);
await writeFile('records/worker-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),method:'In-memory R2 contract tests; synthetic fixtures confined to tests, never stored in production',checks},null,2)+'\n');console.log(JSON.stringify({passed:checks.length}));
