// Platform owner-private dispatch is the access boundary. Do not publish this Site
// publicly without replacing authorization for all write routes.
const API='https://jobicy.com/api/v2/remote-jobs?count=100';
const VERSION='keywords-v2-worker';
const SCOPE='jobicy:first-page:100:unfiltered';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const hash=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join('');
export const plain=v=>String(v??'').replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<[^>]+>/g,' ').replace(/&#(x[0-9a-f]+|[0-9]+);/gi,(_,n)=>{const c=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):parseInt(n);return c>0&&c<=0x10ffff?String.fromCodePoint(c):' ';}).replace(/&(amp|lt|gt|quot|apos|nbsp);/gi,(_,n)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '}[n.toLowerCase()])).replace(/\s+/g,' ').trim();
export async function normalize(j){if(!Number.isInteger(j.id)||j.id<=0||!/^https:\/\/jobicy\.com\/jobs\/[^\s]+$/.test(j.url))throw new Error('invalid_source_record');const title=plain(j.jobTitle),company=plain(j.companyName);if(!title||!company)throw new Error('missing_required_field');const description=plain(j.jobDescription),text=title+' '+description;const skills=Object.entries(SKILLS).flatMap(([skill,pattern])=>{const matched=[...text.matchAll(new RegExp(pattern,'gi'))].map(m=>m[0].toLowerCase());return matched.length?[{skill,matched:[...new Set(matched)].sort()}]:[]});const record={id:String(j.id),title,company,url:j.url,location:plain(j.jobGeo)||'未标注',categories:(j.jobIndustry||[]).map(plain),types:(j.jobType||[]).map(plain),level:plain(j.jobLevel)||'未标注',publishedAt:j.pubDate,skills,source:'Jobicy',availability:'采集时出现在来源列表；未单独核验招聘状态',descriptionHash:await hash(description)};record.recordHash=await hash(JSON.stringify(record));return record;}
const read=async(bucket,key)=>{const o=await bucket.get(key);return o?o.json():null};
const write=(bucket,key,value,options={})=>bucket.put(key,JSON.stringify(value),{httpMetadata:{contentType:'application/json'},...options});
const snapshotKey=s=>'snapshots/'+s.observedAt+'.json';
async function storeSnapshot(bucket,s){const k=snapshotKey(s);await write(bucket,k,s,{onlyIf:{etagDoesNotMatch:'*'},customMetadata:{observedAt:s.observedAt,count:String(s.jobs.length),responseSha256:s.responseSha256,extractorVersion:s.extractorVersion}});return k;}
async function bootstrap(bucket){const exists=await bucket.head(snapshotKey(BASELINE));if(!exists)await storeSnapshot(bucket,BASELINE);return {status:exists?'already_seeded':'seeded',observedAt:BASELINE.observedAt,count:BASELINE.jobs.length};}
async function listHistory(bucket){const objects=[];let cursor;do{const result=await bucket.list({prefix:'snapshots/',limit:1000,include:['customMetadata'],...(cursor?{cursor}:{})});objects.push(...result.objects);cursor=result.truncated?result.cursor:null;}while(cursor);return objects.map(o=>({key:o.key,observedAt:o.customMetadata.observedAt,count:Number(o.customMetadata.count),responseSha256:o.customMetadata.responseSha256,extractorVersion:o.customMetadata.extractorVersion})).sort((a,b)=>a.observedAt.localeCompare(b.observedAt));}
export function compare(previous,current){if(previous.extractorVersion!==current.extractorVersion||previous.sourceScope!==current.sourceScope)return {comparable:false,reason:'采集或提取版本不同，暂不比较'};const old=new Map(previous.jobs.map(j=>[j.id,j])),now=new Map(current.jobs.map(j=>[j.id,j]));return {comparable:true,firstSeen:[...now.keys()].filter(id=>!old.has(id)),notInLatestSample:[...old.keys()].filter(id=>!now.has(id)),changed:[...now.keys()].filter(id=>old.has(id)&&old.get(id).recordHash!==now.get(id).recordHash)};}
async function dataResponse(bucket){const history=await listHistory(bucket);const latest=history.length?await read(bucket,history.at(-1).key):BASELINE;const previous=history.length>1?await read(bucket,history.at(-2).key):null;const state=await read(bucket,'state/sync.json')||{status:'not_run',lastSuccessAt:latest.observedAt};const schedule=await read(bucket,'state/schedule.json')||{enabled:false,status:'not_configured'};const ageHours=(Date.now()-Date.parse(latest.observedAt))/3600000;return {...latest,history:history.length?history.map(({key,...h})=>h):[{observedAt:BASELINE.observedAt,count:BASELINE.jobs.length,responseSha256:BASELINE.responseSha256}],dictionarySize:Object.keys(SKILLS).length,comparison:previous?compare(previous,latest):null,syncInfo:{...state,schedule,storage:history.length?'r2':'baseline_fallback',freshness:ageHours>36?'stale':'fresh',ageHours:Math.round(ageHours*10)/10}};}
async function sync(bucket,fetcher=fetch){await bootstrap(bucket);const current=await dataResponse(bucket),now=new Date(),at=now.toISOString(),day=at.slice(0,10);if(current.observedAt.slice(0,10)===day||now-Date.parse(current.observedAt)<20*3600000)return json({status:'not_due',observedAt:current.observedAt,nextEligibleAt:new Date(Date.parse(current.observedAt)+20*3600000).toISOString()});
 const priorState=await read(bucket,'state/sync.json');if(priorState?.lastAttemptAt&&now-Date.parse(priorState.lastAttemptAt)<3600000)return json({status:'attempt_rate_limited',retryAfter:3600},409);
 // Durable hourly attempt claim; no delete, no blind retries and no concurrent fetches.
 const claim=await write(bucket,'attempts/'+at.slice(0,13)+'.json',{attemptedAt:at,status:'started'},{onlyIf:{etagDoesNotMatch:'*'}});if(!claim)return json({status:'already_attempted_this_hour'},409);
 const old=await read(bucket,'state/sync.json')||{};await write(bucket,'state/sync.json',{...old,status:'running',lastAttemptAt:at});
 try {const r=await fetcher(API,{headers:{Accept:'application/json','User-Agent':'JobChangeObservatory/0.2'},signal:AbortSignal.timeout(35000)});if(!r.ok)throw new Error('source_http_'+r.status);const bytes=await r.arrayBuffer();if(bytes.byteLength>5e6)throw new Error('source_response_too_large');const raw=new TextDecoder().decode(bytes),body=JSON.parse(raw);if(body.success===false||!Array.isArray(body.jobs)||!body.jobs.length||body.jobs.length>100)throw new Error('invalid_source_response');const jobs=[],seen=new Set();for(const j of body.jobs){const item=await normalize(j);if(!seen.has(item.id)){seen.add(item.id);jobs.push(item);}}const observedAt=new Date().toISOString();const snap={schemaVersion:2,observedAt,source:'Jobicy',sourceUrl:API,sourceScope:SCOPE,documentation:'https://jobicy.com/jobs-rss-feed',responseSha256:await hash(raw),responseJobCount:body.jobs.length,pageCount:1,hasMore:body.hasMore,nextCursorPresent:!!body.nextCursor,scope:BASELINE.scope,extractorVersion:VERSION,jobs};await storeSnapshot(bucket,snap);const state={status:'succeeded',lastAttemptAt:at,lastSuccessAt:observedAt,lastError:null,count:jobs.length};await write(bucket,'state/sync.json',state);await write(bucket,'runs/'+at+'.json',state);return json({status:'succeeded',observedAt,count:jobs.length,responseSha256:snap.responseSha256});}
 catch(e){const safe=/^(source_http_\d+|invalid_source_response|source_response_too_large|invalid_source_record|missing_required_field)$/.test(e.message)?e.message:'collection_failed';const state={status:'failed',lastAttemptAt:at,lastSuccessAt:current.observedAt,lastError:safe};await write(bucket,'state/sync.json',state);await write(bucket,'runs/'+at+'.json',state);return json({...state,preservedPreviousSnapshot:true},502);}}
export default {async fetch(request,env){const url=new URL(request.url),path=url.pathname;try{if(path.startsWith('/api/')){if(!env.BUCKET)return json({error:'storage_unavailable'},503);if(request.method==='GET'&&path==='/api/data')return json(await dataResponse(env.BUCKET));if(request.method==='GET'&&path==='/api/status'){const d=await dataResponse(env.BUCKET);return json({observedAt:d.observedAt,snapshots:d.history.length,...d.syncInfo});}if(request.method==='POST'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({error:'origin_not_allowed'},403);if(path==='/api/bootstrap')return json(await bootstrap(env.BUCKET));if(path==='/api/sync')return await sync(env.BUCKET);if(path==='/api/schedule-status'){const body=await request.json();if(typeof body.enabled!=='boolean'||typeof body.description!=='string'||body.description.length>160)return json({error:'invalid_schedule_metadata'},400);await write(env.BUCKET,'state/schedule.json',{enabled:body.enabled,description:body.description,verifiedAt:new Date().toISOString()});return json({status:'saved'});}}return json({error:'method_or_route_not_allowed'},405);}
if(request.method!=='GET'&&request.method!=='HEAD')return new Response('Method not allowed',{status:405});const asset=ASSETS[path==='/'?'/index.html':path];if(!asset)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:asset.body,{headers:{'content-type':asset.type,'cache-control':'no-cache','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});
}catch(e){console.error('job_observatory_request_failed',e?.message);return json({error:'storage_or_runtime_unavailable',message:'历史数据暂不可用；未覆盖已有快照'},503);}}};
export {bootstrap,sync,dataResponse};
